### ISSUE TITLE
kr ios: ingame drag/zoom issues

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#1549]
Ticket: 79578

> This happens randomly - when playing a level the screen will randomly bug out. This bug is weird because it has stages to it: 1. You won't be able to move or interact with the screen at all. After a few seconds It'll work again but it'll be very buggy 2. Once it starts to work again and you interact with the screen, it begins to bug out. If you try to move your screen around the map, the screen zooms in & out and teleports around the map. Both at random. 3. Once the screen is done spazzing out, it'll be stuck in zoom in/zoom out mode. If you try moving the screen up/down/left/right, it's just gonna zoom in/out. Once the bug has reached stage 3, it can be easily fixed by opening and closing the pause menu. Please look into this as it renders you useless during a level for roughly 10-15 seconds. This probably seems really confusing. I can try to provide a more in depth explanation if you need me to.

**Comment by R41N6OW** [comment]
Heyy I figured out how to replicate this a few days ago. The issue happens when you try to drag and you end up dragging over the spells in the bottom left. It bugs out when you go over one of the spells and doesn't drag. Once you drag over a spell the screen will be stuck in zoom mode and might glitch around too. 

![E4A302C3-AA05-4B7D-9F4D-60DA0EBB9F21](https://user-images.githubusercontent.com/95309454/144253849-323d9046-11e3-4890-86aa-fc4d92652bb6.jpeg)

**Comment by cigumo** [comment]
Thanks @R41N6OW !!  I can fix it now :D

**Comment by cigumo** [comment]
fixed in 5.6.07

**Comment by R41N6OW** [comment]
Ok I'm back at this again because I didn't fully test this in my last report. The issue applies to EVERY possible button on screen (excluding the pause button). Earlier I said it happens when you drag over the spells and release while dragging over the spells (which is true) but it also applies to everything. This is the full list of bugged buttons in the current game version: [bottom left spell buttons], [top left hero icon], [bottom right items button], [wave caller button], [tower build button], [tower sell button], and [ANY tower upgrade button]. You might have discovered this and fixed them all when you went to fix the spells but I figured I'd still report it in case you didn't :)
![1E090C7E-4C77-4DB3-859D-3A51CB393EB1](https://user-images.githubusercontent.com/95309454/144927442-9cafb87b-0847-4d9e-b9ee-47ee0c3942a1.jpeg)

**Comment by cigumo** [comment]
Thanks @R41N6OW  :)  I've fixed most of them already but missed the wave flags and tower menu buttons 🤦

**Comment by cigumo** [comment]
There's also the enemy and next wave alert buttons!  haha
<img width="102" alt="Screen Shot 2021-12-06 at 20 56 31" src="https://user-images.githubusercontent.com/934821/144941511-b0e709e4-776d-4724-adfb-4766316aeff1.png">

**Comment by R41N6OW** [comment]
Frontiers will need fixing too. I remembered that Frontiers had a game engine update so I just checked to see if the bug was apparent in Frontiers and it is. I'm assuming it's an issue with whatever was changed in the engine updates.

**Comment by cigumo** [comment]
Sure, it's the same code. Fixing one fixes all three :)
