### ISSUE TITLE
T Bauer: difficulty of sunken citadel, issues with panning and powers

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#17]
https://play.google.com/apps/publish?account=6098018911218203911#ReviewDetailsPlace:p=com.ironhidegames.android.kingdomrushfrontiers&reviewid=gp:AOqpTOG5xCdxDgc9ihOWIQtP1VXOZ_mm0yJE_xqRKGv9QRTPy50yAwD_Ifr_ufMuI0sbgyO-uCOEiAKj7ziy8g

se queja de cambios en gameplay. Por favor preguntale si nos puede dar más detalles de cuales heroes, cuales poderes, cuales niveles. ¿A que se refiere con mobile cannon y donde es que lo usaba?

**Comment by luciag27** [comment]
"You responded to a review I left, asking me to contact you. A couple weeks ago, the game changed.  I play the Sunken Citadel often.  It's not as if I'm counting, but I've started that level probably hundreds of times. I've completed it many times 3 stars, without using special items.  Now, it's basically impossible.  If it isn't, it certainly isn't possible the way I was able to beat it so many times.  

What has changed?  Seemingly everything.  The screen size formatting changed so I to adjust the screen size to play it on my phone.  If the screen is zoomed out all the way, it's too small for practical viewing.  The most annoying aspect is the screen shifts when I go to place reinforcements.  Often the screen will shift, not allowing me to place them where I want, and if it shifts to another position where they can be placed, it will place them there.  It will do the same with cataclysm, except that can be dropped anywhere, which often harmlessly drops in the water.  I use Sha'tra. His special power where he uses a spaceship to lift out any enemy is key.  Before this change, he would almost always lift out a bloodshell when needed.  Now, he almost never does.  If he does anything he will usually take a weak enemy.  Beating the bloodshells are key to beating the level.  They seem to be adjusted to take just enough damage to break through your defense.  I just played. The first bloodshed took at least 8 hits from an archmage with fully upgraded twister and nevery warped him.  What is the point if a fully upgraded tower will not do it's job?  My opinion is as I stated, bloodshells are adjusted to beat defenses.  Sha'Tra was there the whole time and never lifted him out.  Again, it seems as if they are there adjusted to break your defense regardless of how you are setup.  It's minor, but proves the game has changed,  I use to be able to place my battle-mecha on the little point right next to the bridge. Now, it must stay on the path.

I don't know if the level is impossible now.  If it's not, it's close without using special items.  I can barely 3 star the level using 5 extra bags of gold, which is an enormos advantage.  Again, a level I beat numerous times, without aids.  I've played that level enough to know exactly when a bloodshell needs to be defeated and they almost never are.  It's not a matter of shifting defenses, I've had enemies pass defenses in multiple places at the same time.  

If the game was free, probably not a big deal.  If the game started this way, I would say it's too difficult, but ok.  I don't think it's right to change randomly though.  I've read the Pandaemonium level in the other game is extremely difficult from other people. I can 3 star that level everytime, it's a cake walk compare to The Sunken Citadel.... now.

Like I said, I don't know if the level is impossible straight up now.  I do know the way I've beaten it 50.. maybe a 100 times isn't remotely close to working now.  It's a shame because the game use to be fun."


Samsung Galaxy S5. Android 6.0.1

KR2-phone-3.0.25

**Comment by cigumo** [comment]
@luciag27 : decile que se lo vamos a arreglar, pero que nos de un poco de tiempo porque estamos con bugs mas críticos primero (save game!).
Invitalo a ser beta tester.  :)

**Comment by cigumo** [comment]
@luciag27 sabes si esta de beta tester?

**Comment by cigumo** [comment]
@luciag27 necesitaria chatear con el  o intercambiar algun email. tenes el contacto? 
Sino invitalo al discord de krf-android
