### ISSUE TITLE
review all special enemy attacks for stun interruptions

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#324]
to fix: 
- [x] heretic consume and servant
- [x] arachnomancer spawn
- [x] webspitter spider (interrupted by timelapse only)
- [x] heretic attacks (check with vindicator also)  https://streamable.com/qpzz2
  - check it fixes wild magus eldritch ![sprite overlap](https://cdn.discordapp.com/attachments/423213564644556822/498526520936103946/Eldritch_Doom_and_Grip_of_Darkness.jpg)
  - https://streamable.com/6ecr3
- [x] razorboar (check if it's possible)

**Comment by PitNata** [comment]
Heretic's both skills are uninterruptable
Arachnomancer summon is uninterruptable
Webspitter Spider is half-uninterruptable (Timelapse interrupts)
Drider is interruptable
Golem is interruptable
Scourger is interruptable
Razorboar cannot be interrupted due to no "standby" status
Evoker is interruptable (needs more testing)

**Comment by sunnydaler** [comment]
Bandersnatch's spine attack can be interrupted.

**Comment by sunnydaler** [comment]
Check Vindicator too.

**Comment by cigumo** [comment]
- fixed all above
- added interrupt to avenger's last service, blighter, ettin insane, scourger lash and evoker in some cases
