### ISSUE TITLE
KR3 Bug questions for the testers

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#58]
# Questions about alpha testing

## Unknown
- [ ] on Crystal lake map death animation for enemies is skipped sometimes, they just freeze for a bit and then disappear, i think this is caused by those little dragons as well
  - can't reproduce
- [ ] on Crystal lake map bow shooting solders aim at the ground instead of the enemies that appear from crystal path
  - can't reproduce

## AerisDraco
- [x] Sorcerer Stone freeze has the look of a Faery Dragon crystallize.  / AerisDraco
  - I can't see any difference
  - ![](https://cdn.discordapp.com/attachments/351061032262696961/481609399778148352/unknown.png)
- [x] ...finish off Hi-Hi Enha, and they killed him, but his death did not trigger the normal "kill every other enemy on screen". / AerisDraco A1
  - could not reproduce it
- [x] Encyclopedia Tower damage text (specifically mage) seems to be small. / AerisDraco A1
  - Which one? Encyclopedia, in-game infobar, in-game tooltip footer?
    - Encyclopedia tower details text
- [ ] Wave 5 on Shrine was autocalled. / AerisDraco
  - could not reproduce

## GeminiSparkSP
- [x] level 8, and it shows new enemy notifications for Cutthroats, Hoplites, and Harassers, and the notification for poison fungus / GeminiSparkSP A2
  - to test again with beta, because notifications were enabled later and the seen flags weren't probably set earlier.
- [ ] A Twilight Avenger got frozen by the dragon, and then teleported back / GeminiSparkSP A2
  - don't understand this bug
- [ ] The game stops responding when I played the minigame in Neverwonder / GeminiSparkSP A2
  - can't reproduce
- [x] Eridan's arrow rain spell has inconsistent hitbox / GeminiSparkSP A1
  - _Do you mean compared to the mobile version? I can't see any difference._
- [ ] In-game pause menu doesn't have a title on the header / GeminiSparkSP A1
  - _I can see the "Options" title. Can you please send a screen shot?_
- [ ] Units sometimes doesn't return to their original position after fighting. This happens with Eridan a lot / GeminiSparkSP A1
  - _It would be great if you could provide more details, because I can't reproduce it for the moment._

## PitNata
- [ ] 1. Cloud Stalkers have some strange bug regarding their damage. If they die, the they/it may still damage the target contionusly, when it dies, it will not spawn any Cloud Stalkers. / PitNata A1
  - I can't reproduce this one. 
- [ ] 2. Gnoll Catapults are too slow when moving. Do not know if it's intentional. / PitNata A1
  - they seem ok.
- [x] 3. Blade Dance when initiated, can attack longer than it was on Mobile. Do not know if it's intentional. / PitNata A1
  - can't find any differences with the mobile. can you be more specific? 
  - cigumo/kr-love#255
- [x] 4. Weirdwoods may become stucked and not attacking when using Clobber skill. / PitNata A1
  - can't reproduce it. is it related to a specific stage? 
- [ ] 5. Gloomy, Rabbit, Bandersnatch sprites are missing, but those units still functions. [Related to particular OC?] / PitNata A1
- [x] 6. If Catha is blocking an enemy at the time, if she dies, the unit is stuck too, but he can be killed. Catha will not revive in this state. / PitNata A1
  - cant reproduce
  - cigumo/kr-love#256
- [x] 7. Fairy Tale's animation skill de-sync. Textures for Pixies are being brought to place with delay, animation which Catha does, is not affected. (Bug not understood how it works, it seems it based on path) / PitNata A1
  - cant reproduce
  - cigumo/kr-love#257
- [x] 8. Denas can solo Hi-Hi Enha on Veteran / PitNata A1
  - cant reproduce
  - cigumo/kr-love#258
- [x] 9. Heroic Mactan's Retreat finishes even though you haven't killed all of enemies (I hadn't killed the last Drider, and the game finished afterwards) / PitNata A1
  - can't reproduce
  - cigumo/kr-love#259

## SealDarklight
- [x] Weirdwoods tend to often freeze or do nothing / SealDarklight A1
  - can't reproduce it. is it related to a specific stage? 
- [x]  Eridans Hero Spell seemed to deal little to no damage if i tab it on the enemies but it works if you put it enemies ahead but it deals damage half the times.  / SealDarklight A2
  - can't reproduce
- [ ] After you defeat stage 11s boss fight (Which is Malicia) the game will trigger a cutscene but after that the game doesn't automatically give you stage complete unless you moved your hero / SealDarklight A2
  - can't reproduce
- [ ] Bravebarks Natures wrath seem to only freeze the game if i use the spell on the southern exit / SealDarklight A2
  - which stage? 

## VirtualTT
- [ ] Also I find inconvenient the way spider boss selection works when it jumps into the battle field. Especially on the last level when it jumps somewhere in the middle. It seems like there is no hitbox while descends or ascends. It is rather difficult to catch the exact moment when the hitbox appears and disappears so I tend to click random stuff below it a lot (including accidentally selling towers).
  - The Spider Goddess or Mactans dropping from it's web to block towers, or spawn spiders?

**Comment by PitNata** [comment]
Bug №3: Blade Dancer seems to have an activation range that is when enemies come close, but the Bladesingers will continue to perform the Blade Dance and attack enemies from a longer range.
Bug №4: This bug is related to what AerisDraco reported, about Weirdwoods.
Bug №6: This bug works in a way, if you do not upgrade any of Catha's abilities, or Reset them and starting the stage. She will then use the skills that is not upgraded, and so unloaded, in which she will stiuck and then this bug may occur.
Bug №7: The bug occurs when the Fairy Tale skill level is either 1 or 2, on 3 level it does happen infrequently. the Animation itself is bugged to a point, at which the texture of summoned pixies do not place itself properly, until some moments later, it will position itself right where it is. I can't really describe it, but it is how does happen.
Bug №8: To make Denas be able to withstand the damage of Hi-Hi Enha, he must have level higher than 8, and having a Sybarite skill level up to max, in which when his health goes at critical levels, he will heal himself every time it goes to that level. he will then without any units interrupting him (as well as no towers helping him) he can kill Hi-Hi Enha one on one.
Bug №9: I think this bug is related to Driders, as they have ability to hatch and spawn new Driders within your units. So, some *unneeded* units if they get spawned after everybody is killed, when finally spawns, the game will end-fast, while the Drider is not dead.
