### ISSUE TITLE
CDs of Harasser's arrow volley and shadow jump

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#584]
- [x] Arrow Volley (4 arrows)
On Steam, it seems like they perform this once, and then shoot just 1 arrow after shadow jumping.
On mobile, the animation is 1.3 seconds long and the cooldown is about 18 seconds (I am not sure about it ).

- [x] Shadow Jump
On Steam, Shadow Jump's animation is 0.8 second long and the cooldown is 5 seconds.
It is about 12 seconds on mobile.

**Comment by cigumo** [comment]
changed in 1.3.1

On mobile, Harasser cooldown is increased in specialPower instead of updateSpecialPowerCooldowns.  This lead to the counter not being increased while the enemy is charging (melee fight). For the harasser case, as the animation is 25 frames and the charge time is 24, due to rounding it can generate a "capture" effect where it's not released for twice or more the cooldown time of 5 secs. 
I've changed the cooldown to 7 secs which gives a more reasonable behaviour while not doing the capture effect.

**Comment by cigumo** [comment]
Also fixed in 1.3.1 is the volleys only shot once per enemy.
