### ISSUE TITLE
Redcap Death Strike and regeneration

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#724]
- [ ] If Death Strike procs on a parrying Bladesinger, redcap gains regeneration. 
![bladesingers](https://user-images.githubusercontent.com/43391939/54435275-77e7c580-4773-11e9-8654-4a2373f20524.gif)
Remark: if it misses on Lynn, Red Cap doesn't heal.
![lynn](https://user-images.githubusercontent.com/43391939/54435296-82a25a80-4773-11e9-9a86-ae1fb3186ebe.gif)

- [ ] If Death Strike procs in a row (https://streamable.com/y4r9a) or procs again before the regeneration gained from previous Death Strike wears out (https://streamable.com/8xsuo), the latter Death Strike doesn't give Redcap regeneration. I think the regen duration should overlap.

**Comment by sunnydaler** [comment]
This time, redap's death strike proced twice successively and still dies without getting any regeneration.
![deathstrike](https://user-images.githubusercontent.com/43391939/54468945-2a9c4000-47d5-11e9-8b53-85424bd21faa.gif)
what is causing the inconsistency?
Video links:
Redcap regens: https://streamable.com/i10tp
Redcap doesn't regen: https://streamable.com/gjqcn

**Comment by cigumo** [comment]
The problem is that it's showing the blood fx even if the death blow is dodged. 
Also, while parrying, the soldier is invuln, but does not dodge the attacks, so the fx and the heal can happen. 

In 4.0.01 I've changed the blood fx not to show if the attack is dodged, so if the blood shows the heal happens.
