### ISSUE TITLE
Twister 

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#731]
- [x] in love, It is not triggered on flying enemies and can't capture even indirectly.

- [x]  it is a moving AoE, then should Twister be able to capture invisible Nightscales indirectly?

- [x] in love, Twister animation's duration is 176/192/252 frames @ 30fps.
there is little difference between level 1 and 2.  Is level 1 twister's duration OK?

**Comment by cigumo** [comment]
in cocos 
- it does not trigger with flying enemies
- it does not capture invisible nightscales 
- twister duration depends on path nodes, so the shape of the path affects the time it will be shown.
- twister stays on one half side of the road because of how it was coded, this is different in love where it covers the whole road properly. 

fixed in kr2-console-3.2.00
- capture flying enemies
